server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        autoindex off;

        # PDF files only
        location ~* \.pdf$ {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods GET;
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }

        # Deny non-PDF access
        location ~* \.(?!pdf$)[^.]+$ {
            return 403;
        }
    }
}
